version: 2.0

jobs:
   build:
     docker:
       - image: circleci/openjdk:8-jdk-browsers
         environment:
           WAR_FILE_NAME: mentoring-0.0.1-SNAPSHOT.war
     steps:
       - checkout
       - restore_cache:
           key: mentoring-{{ checksum "pom.xml" }}
       - run: mvn dependency:go-offline
       - run: mvn clean install -DskipTests
       - save_cache:
           paths:
             - ~/.m2
           key: mentoring-{{ checksum "pom.xml" }}
       - store_artifacts:
           path: target/WAR_FILE_NAME
   test:
     docker:
       - image: circleci/openjdk:8-jdk-browsers
     steps:
       - checkout
       - restore_cache:
           key: mentoring-test-{{ checksum "pom.xml" }}
       - run: mvn test
       - save_cache:
           paths:
             - ~/.m2
           key: mentoring-test-{{ checksum "pom.xml" }}
       - store_test_results:
           path: target/surefire-reports
   deploy:
     docker:
       - image: circleci/openjdk:8-jdk-browsers
     steps:
       - checkout
       - run: echo "deploy"
       
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
