version: 2.0

defaults: &defaults
   docker:
     - image: circleci/openjdk:8-jdk-browsers
       environment:
         WAR_FILE_NAME: mentoring-0.0.1-SNAPSHOT.war

jobs:
   build:
     <<: *defaults
     steps:
       - checkout
       - restore_cache:
           key: mentoring-{{ checksum "pom.xml" }}
       - run: mvn dependency:go-offline
       - run: mvn clean install -DskipTests -P prod
       - save_cache:
           paths:
             - ~/.m2
           key: mentoring-{{ checksum "pom.xml" }}
       - store_artifacts:
           path: target/mentoring-0.0.1-SNAPSHOT.war
           destination: mentoring-0.0.1-SNAPSHOT.war
       - persist_to_workspace:
           root: target
           paths:
              - mentoring-0.0.1-SNAPSHOT.war
   test:
     <<: *defaults
     steps:
       - checkout
       - restore_cache:
           key: mentoring-test-{{ checksum "pom.xml" }}
       - run: mvn test
       - save_cache:
           paths:
             - ~/.m2
           key: mentoring-test-{{ checksum "pom.xml" }}
       - store_test_results:
           path: target/surefire-reports
   deploy:
     <<: *defaults
     steps:
       - checkout
       - attach_workspace:
           at: target
       - run: wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
       - run: heroku plugins:install heroku-cli-deploy
       - run: heroku war:deploy target/$WAR_FILE_NAME --app $HEROKU_APP_NAME

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
