version: 2.0

jobs:
   build:
     docker:
       - image: circleci/openjdk:8-jdk-browsers
     steps:
       - checkout
       - restore_cache:
           key: imbd-{{ checksum "pom.xml" }}
       - run: mvn dependency:go-offline
       - save_cache:
           paths:
             - ~/.m2
           key: imbd-{{ checksum "pom.xml" }}
       - run: mvn package
       - store_artifacts:
           path: target/imbd-SNAPSHOT.war
   test:
     docker:
       - image: circleci/openjdk:8-jdk-browsers
     steps:
       - checkout
       - run: mvn test
       - store_test_results:
           path: target/surefire-reports
   deploy:
     docker:
       - image: circleci/openjdk:8-jdk-browsers
     steps:
       - checkout
       - run: echo "pp"
       
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
